sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t boltgun69/docker-react-demo .

# script:
#   - docker run -e CI=true boltgun69/docker-react-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "eb-docker-demo-tci"
  env: "eb-docker-demo-tci-env"
  bucket_name: "elasticbeanstalk-us-west-1-815332568426"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
